/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as ApiPublicKeepAliveRouteImport } from './routes/api/public/keep-alive'
import { Route as ApiPublicSendDuePushRouteImport } from './routes/api/public/send-due-push'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKeepAliveRoute = ApiPublicKeepAliveRouteImport.update({
  id: '/api/public/keep-alive',
  path: '/api/public/keep-alive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendDuePushRoute = ApiPublicSendDuePushRouteImport.update({
  id: '/api/public/send-due-push',
  path: '/api/public/send-due-push',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/vendas': typeof VendasRoute
  '/api/public/keep-alive': typeof ApiPublicKeepAliveRoute
  '/api/public/send-due-push': typeof ApiPublicSendDuePushRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/vendas': typeof VendasRoute
  '/api/public/keep-alive': typeof ApiPublicKeepAliveRoute
  '/api/public/send-due-push': typeof ApiPublicSendDuePushRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/vendas': typeof VendasRoute
  '/api/public/keep-alive': typeof ApiPublicKeepAliveRoute
  '/api/public/send-due-push': typeof ApiPublicSendDuePushRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/vendas'
    | '/api/public/keep-alive'
    | '/api/public/send-due-push'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/vendas'
    | '/api/public/keep-alive'
    | '/api/public/send-due-push'
  id:
    | '__root__'
    | '/'
    | '/reset-password'
    | '/vendas'
    | '/api/public/keep-alive'
    | '/api/public/send-due-push'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VendasRoute: typeof VendasRoute
  ApiPublicKeepAliveRoute: typeof ApiPublicKeepAliveRoute
  ApiPublicSendDuePushRoute: typeof ApiPublicSendDuePushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/keep-alive': {
      id: '/api/public/keep-alive'
      path: '/api/public/keep-alive'
      fullPath: '/api/public/keep-alive'
      preLoaderRoute: typeof ApiPublicKeepAliveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-due-push': {
      id: '/api/public/send-due-push'
      path: '/api/public/send-due-push'
      fullPath: '/api/public/send-due-push'
      preLoaderRoute: typeof ApiPublicSendDuePushRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VendasRoute: VendasRoute,
  ApiPublicKeepAliveRoute: ApiPublicKeepAliveRoute,
  ApiPublicSendDuePushRoute: ApiPublicSendDuePushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
